package com.plusmall.mapper;

import com.plusmall.model.TbBrand;

public interface TbBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Sun Feb 10 10:38:34 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Sun Feb 10 10:38:34 CST 2019
     */
    int insert(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Sun Feb 10 10:38:34 CST 2019
     */
    int insertSelective(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Sun Feb 10 10:38:34 CST 2019
     */
    TbBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Sun Feb 10 10:38:34 CST 2019
     */
    int updateByPrimaryKeySelective(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Sun Feb 10 10:38:34 CST 2019
     */
    int updateByPrimaryKey(TbBrand record);
}