package com.plusmall.mapper;

import com.plusmall.model.TbSeckillGoods;
import com.plusmall.model.TbSeckillGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int countByExample(TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int deleteByExample(TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int insert(TbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int insertSelective(TbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    List<TbSeckillGoods> selectByExample(TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    TbSeckillGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSeckillGoods record, @Param("example") TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int updateByExample(@Param("record") TbSeckillGoods record, @Param("example") TbSeckillGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int updateByPrimaryKeySelective(TbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbggenerated Wed Apr 03 23:17:45 CST 2019
     */
    int updateByPrimaryKey(TbSeckillGoods record);
}